### PR TITLE
Correct and simplify symbolic link creating code

### PR DESCRIPTION
**Pull request by trevorld**

### CODE REVIEW

**Comment by kbroman** [comment]
Thanks for your suggestion. Need to get rid of the `../` though, right?

```shell
ln -s ReadMe.md inst/README.md
```

And the original version should work, right? If you `cd` into `inst/`, you can just do `ln -s ../ReadMe.md`

**Comment by trevorld** [comment]
Doesn't the original version need to be:

    ln -s ../ReadMe.md README.md

Otherwise how does ``ln`` know how the symbolic link should be renamed?  Also I'm pretty sure you need the ``../`` in my suggested improvement:
                      

````
trevorld@stoic-sloth:~/a/projects/R/optparse$ ln -s README.rst inst/README                                                                                                                             
trevorld@stoic-sloth:~/a/projects/R/optparse$ cat inst/README                                                                                                                                          
cat: inst/README: No such file or directory                                                                                                                                                            
trevorld@stoic-sloth:~/a/projects/R/optparse$ rm inst/README                                                                                                                                           
trevorld@stoic-sloth:~/a/projects/R/optparse$ ln -s ../README.rst inst/README                                                                                                                          
trevorld@stoic-sloth:~/a/projects/R/optparse$ cat inst/README | head
optparse                                         
========                                         

.. image:: https://www.r-pkg.org/badges/version/optparse                                           
    :target: https://cran.r-project.org/package=optparse                                           
    :alt: CRAN Status Badge                      

.. image:: https://travis-ci.org/trevorld/optparse.png?branch=master                               
    :target: https://travis-ci.org/trevorld/optparse                                               
    :alt: Build Status                           
````

**Comment by kbroman** [comment]
But this whole business is for the case that you want the file to be `ReadMe.md`. If you go with `inst/README.md`, then you might as well have the original file be called `README.md`, in which case you can just skip this section&mdash;there's no reason to put it in `.Rbuildignore` with this symbolic link in `inst/`.

**Comment by trevorld** [comment]
Oh sorry, I thought you wanted the file to be ReadMe.md on Github and README.md on CRAN as per https://cran.r-project.org/doc/manuals/R-exts.html#Package-structure.  If you do it your way does CRAN turn ReadMe.md into nicely formatted HTML like it does with README.md?

**Comment by kbroman** [comment]
CRAN ignores it; moves everything out of `inst/` into root directory when installing the package.

**Comment by kbroman** [comment]
Maybe I should just delete that whole section.

**Comment by trevorld** [comment]
That might be a good idea.  I can see the value in writing a README in one the several markup languages supported by Github other than markdown but I don't really see the value (if you have a public Github repo) of bundling a non-standardly-named README with your package tarball if your users can't easily see it on your CRAN package page.

**Comment by kbroman** [comment]
Okay, thanks: now deleted.

**Pull request closed without merging**
